user nginx;
worker_processes auto;

events {}

http {
    # Definir formato de log con ubicación
    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                     '$status $body_bytes_sent "$http_referer" '
                     '"$http_user_agent" "$http_x_forwarded_for" '
                     'location=$request_uri';  # Esta línea nos dice en qué ubicación entra

    access_log /var/log/nginx/access.log main;  # Archivo de log de acceso

    error_log /var/log/nginx/error.log debug;   # Activar logging en modo debug (mucha información)

    include       mime.types;
    default_type  application/octet-stream;

    # Definir los tipos MIME para los archivos estáticos
    types {
        application/javascript js;
        text/css css;
        application/json json;
        application/manifest+json webmanifest;
        text/html html;
        image/svg+xml svg;
        font/woff2 woff2;
        font/woff woff;
    }

    charset utf-8;
    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name mobile.joinlabs.com.ar;

        root /usr/share/nginx/html;  # Ruta donde se encuentran los archivos de la app Angular (dist/casa-del-renault/browser)
        index index.html;

        # Let's Encrypt challenge para certificados SSL
        location ^~ /.well-known/acme-challenge/ {
            default_type "text/plain";
            allow all;
        }

        # Archivos estáticos correctamente tipados y con caché
        location ~* \.(js|css|json|webmanifest|ico|png|jpg|jpeg|gif|svg|woff2?|ttf|eot|map)$ {
            try_files $uri =404;  # Si el archivo no existe, retorna un 404
            access_log off;  # Desactivar el log de acceso para estos archivos
            expires 1y;  # Expira después de 1 año
            add_header Cache-Control "public, must-revalidate, proxy-revalidate";  # Habilitar caché
        }

        # Service Worker y manifiesto de PWA
        location = /ngsw-worker.js {
            try_files $uri =404;  # Si el archivo no existe, retorna un 404
            add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate";  # Deshabilitar caché para el worker
        }

        location = /manifest.webmanifest {
            try_files $uri =404;  # Si el archivo no existe, retorna un 404
        }

        # Redirigir a index.html para rutas no encontradas (Angular SPA)
        location / {
            try_files $uri $uri/ /index.html;  # Si el archivo no existe, redirige a index.html
        }

        # Seguridad adicional con Strict-Transport-Security para proteger contra ataques Man-in-the-Middle
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    }
}
